services:
  gripl-frontend:
    build:
      context: ./gripl/gripl-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://gripl-backend:8080
    image: gripl-f:latest
    container_name: gripl-frontend
    restart: unless-stopped
    networks:
      - app
    ports:
      - "3000:3000"

  gripl-backend:
    build:
      context: ./gripl/gripl-backend
      dockerfile: Dockerfile
    image: gripl-b:latest
    container_name: gripl-backend
    restart: unless-stopped
    depends_on:
      - gripl-postgres
      - gripl-neo4j
    env_file:
      - .env.local
    environment:
      - FRONTEND_BASE_URL=http://localhost:3000
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gripl-postgres:5432/gripldb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RAG_API_URL=http://gripl-rag:8081
    volumes:
      - playwright-browsers:/root/.cache/ms-playwright
    networks:
      - app
    ports:
      - "8000:8080"

  gripl-rag:
    build:
      context: ./gripl/gripl-rag
      dockerfile: Dockerfile
    image: gripl-rag:latest
    container_name: gripl-rag
    restart: unless-stopped
    depends_on:
      - gripl-neo4j
    env_file:
      - .env.local
    environment:
      - NEO4J_URI=neo4j://gripl-neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=gripl-rag-2026
    volumes:
      - ./gripl/gripl-rag/rag_working_dir:/app/rag_working_dir
      - ./gripl/gripl-rag/data:/app/data
      - huggingface_cache:/root/.cache/huggingface
    networks:
      - app
    ports:
      - "8081:8081"
  gripl-nlpsql:
    build:
      context: ./gripl/gripl-sql-llm
      dockerfile: Dockerfile

    image: gripl-nlpsql:latest

    container_name: gripl-nlpsql

    restart: unless-stopped

    env_file:
      - .env.local

    volumes:

      - huggingface_cache:/root/.cache/huggingface
      - ./gripl/gripl-sql-llm/test.db:/app/test.db

    networks:
      - app

    ports:
      - "8082:8082"

  gripl-neo4j:
    image: neo4j:5-community
    container_name: gripl-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/gripl-rag-2026
    volumes:
      - neo4j_data:/data
    networks:
      - app
    ports:
      - "7474:7474"
      - "7687:7687"

  gripl-postgres:
    image: postgres:15
    container_name: gripl-postgres
    restart: unless-stopped
    volumes:
      - gripl-postgres-data:/var/lib/postgresql/data
    networks:
      - app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gripldb

volumes:
  playwright-browsers:
  gripl-postgres-data:
  huggingface_cache:
  neo4j_data:

networks:
  app:
    external: false
