"""add category table

Revision ID: 508d27f1464d
Revises: 
Create Date: 2026-08-12 10:15:20.430499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508d27f1464d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avv_akteure_id'), table_name='avv_akteure')
    op.drop_table('avv_akteure')
    op.drop_table('recht_pflicht')
    op.drop_table('pflicht_tom')
    op.drop_table('rechtlicher_ausloeser_pflicht')
    op.drop_table('dsgvo_datenkategorie')
    op.drop_table('sicherheitsmassnahmen_schutzziel')
    op.drop_table('pflicht_bedingung')
    op.drop_table('datenpanne_risikofaktor')
    op.drop_table('verstoss')
    op.drop_index(op.f('ix_technische_organisatorisch_masnahmen_id'), table_name='technische_organisatorisch_masnahmen')
    op.drop_table('technische_organisatorisch_masnahmen')
    op.drop_index(op.f('ix_gemeinsame_verantwortlichkeit_id'), table_name='gemeinsame_verantwortlichkeit')
    op.drop_table('gemeinsame_verantwortlichkeit')
    op.drop_index(op.f('ix_voraussetzung_id'), table_name='voraussetzung')
    op.drop_table('voraussetzung')
    op.drop_index(op.f('ix_grund_prinzipien_dsgvo_id'), table_name='grund_prinzipien_dsgvo')
    op.drop_table('grund_prinzipien_dsgvo')
    op.drop_table('gemeinsame_verantwortlichkeit_dsfa')
    op.drop_table('verarbeitung_rechtsgrundlage')
    op.drop_table('uebermittlungs_regelung_ausnahme')
    op.drop_table('aufbewahrungsfrist_zweck')
    op.drop_table('verarbeitung_risikofaktoren')
    op.drop_index(op.f('ix_dsgvo_akteur_id'), table_name='dsgvo_akteur')
    op.drop_table('dsgvo_akteur')
    op.drop_table('gruppe')
    op.drop_table('uebermittlungs_regelung_garantie')
    op.drop_index(op.f('ix_zweck_id'), table_name='zweck')
    op.drop_table('zweck')
    op.drop_table('konsultation_pflichten')
    op.drop_index(op.f('ix_schutzziel_id'), table_name='schutzziel')
    op.drop_table('schutzziel')
    op.drop_table('datenpanne_verarbeitung')
    op.drop_table('dsgvo_ziel')
    op.drop_index(op.f('ix_risikofaktoren_id'), table_name='risikofaktoren')
    op.drop_table('risikofaktoren')
    op.drop_table('verhaltenskodex_prinzip')
    op.drop_table('avv_tomassnahmen')
    op.drop_table('sicherheitsniveau')
    op.drop_table('recht_bedingung')
    op.drop_table('avv_pflichten')
    op.drop_table('auftragsverarbeitungs_vertrag')
    op.drop_index(op.f('ix_vorherige_konsultation_id'), table_name='vorherige_konsultation')
    op.drop_table('vorherige_konsultation')
    op.drop_table('gemeinsame_verantwortlichkeit_pflichten')
    op.drop_table('pflicht')
    op.drop_table('interne_personen_gruppen')
    op.drop_table('bedingung')
    op.drop_table('verarbeitungsform')
    op.drop_table('verarbeitung_frist')
    op.drop_table('rechtsgrundlage_pflicht')
    op.drop_index(op.f('ix_verarbeitungstaetigkeiten_id'), table_name='verarbeitungstaetigkeiten')
    op.drop_table('verarbeitungstaetigkeiten')
    op.drop_table('avv_verarbeitungstaetigkeit')
    op.drop_table('aufbewahrungsfrist')
    op.drop_index(op.f('ix_datenpanne_id'), table_name='datenpanne')
    op.drop_table('datenpanne')
    op.drop_table('ausnahme_pflicht')
    op.drop_table('uebermittlung')
    op.drop_table('gruppe_verarbeitungstaetigkeit')
    op.drop_index(op.f('ix_datenpanne_akteur_id'), table_name='datenpanne_akteur')
    op.drop_table('datenpanne_akteur')
    op.drop_table('compliance_empfehlung')
    op.drop_table('rechtlicher_ausloeser')
    op.drop_table('aufbewahrungsfrist_datenkategorie')
    op.drop_index(op.f('ix_rechtsgrundlage_id'), table_name='rechtsgrundlage')
    op.drop_table('rechtsgrundlage')
    op.drop_table('verarbeitung_zu_tom')
    op.drop_table('gemeinsame_verantwortlichkeit_verarbeitung')
    op.drop_table('pflicht_verstoss')
    op.drop_table('sanktion_verstoss')
    op.drop_index(op.f('ix_verhaltenskodex_id'), table_name='verhaltenskodex')
    op.drop_table('verhaltenskodex')
    op.drop_index(op.f('ix_aufgaben_id'), table_name='aufgaben')
    op.drop_table('aufgaben')
    op.drop_table('verarbeitung_empfaengerkategorie')
    op.drop_table('sicherheitsmasnahme')
    op.drop_table('sanktion')
    op.drop_index(op.f('ix_dsfas_id'), table_name='dsfas')
    op.drop_table('dsfas')
    op.drop_table('verhaltenskodex_akteur')
    op.drop_table('recht')
    op.drop_table('datenpanne_pflichten')
    op.drop_table('uebermittlungs_regelung')
    op.drop_table('tom_zu_schutz_ziel')
    op.drop_table('drittland')
    op.drop_table('recht_akteur')
    op.drop_table('verstoss_strafe')
    op.drop_table('definition')
    op.drop_table('pflicht_grundprinzip')
    op.drop_table('dsgvo_strafen')
    op.drop_table('konsultation_verarbeitung')
    op.drop_table('verhaltenskodex_pflicht')
    op.drop_table('konsultation_behoerde')
    op.drop_table('uebertragungsgarantie')
    op.drop_table('uebermittlungsausnahme')
    op.drop_table('ausnahme')
    op.drop_table('verarbeitung_zu_datenkategorie')
    op.drop_index(op.f('ix_einwilligung_id'), table_name='einwilligung')
    op.drop_table('einwilligung')
    op.drop_index(op.f('ix_gemeinsame_verantwortlichkeit_akteur_id'), table_name='gemeinsame_verantwortlichkeit_akteur')
    op.drop_table('gemeinsame_verantwortlichkeit_akteur')
    op.drop_table('pflichtenkategorie')
    op.drop_table('rechtlicher_ausloeser_bedingung')
    op.drop_table('empfaenger_kategorie')
    op.drop_table('interne_personen_gruppen_verarbeitung')
    op.drop_table('recht_ausnahme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recht_ausnahme',
    sa.Column('recht_id', sa.INTEGER(), nullable=False),
    sa.Column('ausnahme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ausnahme_id'], ['ausnahme.id'], ),
    sa.ForeignKeyConstraint(['recht_id'], ['recht.id'], ),
    sa.PrimaryKeyConstraint('recht_id', 'ausnahme_id')
    )
    op.create_table('interne_personen_gruppen_verarbeitung',
    sa.Column('interne_person_gruppe_id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitungstaetigkeit_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['interne_person_gruppe_id'], ['interne_personen_gruppen.id'], ),
    sa.ForeignKeyConstraint(['verarbeitungstaetigkeit_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('interne_person_gruppe_id', 'verarbeitungstaetigkeit_id')
    )
    op.create_table('empfaenger_kategorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechtlicher_ausloeser_bedingung',
    sa.Column('rechtlicher_ausloeser_id', sa.INTEGER(), nullable=False),
    sa.Column('bedingung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bedingung_id'], ['bedingung.id'], ),
    sa.ForeignKeyConstraint(['rechtlicher_ausloeser_id'], ['rechtlicher_ausloeser.id'], ),
    sa.PrimaryKeyConstraint('rechtlicher_ausloeser_id', 'bedingung_id')
    )
    op.create_table('pflichtenkategorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gemeinsame_verantwortlichkeit_akteur',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gemeinsame_verantwortlichkeit_id', sa.INTEGER(), nullable=False),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.Column('rolle', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['gemeinsame_verantwortlichkeit_id'], ['gemeinsame_verantwortlichkeit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemeinsame_verantwortlichkeit_akteur_id'), 'gemeinsame_verantwortlichkeit_akteur', ['id'], unique=False)
    op.create_table('einwilligung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('einwilligung', sa.VARCHAR(length=500), nullable=False),
    sa.Column('rechtsgrundlage_id', sa.INTEGER(), nullable=True),
    sa.Column('verarbeitungstaetigkeit_id', sa.INTEGER(), nullable=True),
    sa.Column('akteur_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['rechtsgrundlage_id'], ['rechtsgrundlage.id'], ),
    sa.ForeignKeyConstraint(['verarbeitungstaetigkeit_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_einwilligung_id'), 'einwilligung', ['id'], unique=False)
    op.create_table('verarbeitung_zu_datenkategorie',
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.Column('datenkategorie_id', sa.INTEGER(), nullable=False),
    sa.Column('aufbewahrungsfrist_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['aufbewahrungsfrist_id'], ['aufbewahrungsfrist.id'], ),
    sa.ForeignKeyConstraint(['datenkategorie_id'], ['dsgvo_datenkategorie.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('verarbeitung_id', 'datenkategorie_id')
    )
    op.create_table('ausnahme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('gesetzliche_grundlage', sa.VARCHAR(length=255), nullable=False),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('uebermittlungsausnahme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ausnahme', sa.VARCHAR(length=255), nullable=False),
    sa.Column('artikel_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('absatz_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uebertragungsgarantie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bedingung', sa.VARCHAR(length=255), nullable=False),
    sa.Column('artikel_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('absatz_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.Column('erklaerung', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('konsultation_behoerde',
    sa.Column('konsultation_id', sa.INTEGER(), nullable=False),
    sa.Column('behoerde_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['behoerde_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['konsultation_id'], ['vorherige_konsultation.id'], ),
    sa.PrimaryKeyConstraint('konsultation_id', 'behoerde_id')
    )
    op.create_table('verhaltenskodex_pflicht',
    sa.Column('verhaltenskodex_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.Column('praezisierung', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verhaltenskodex_id'], ['verhaltenskodex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verhaltenskodex_id', 'pflicht_id')
    )
    op.create_table('konsultation_verarbeitung',
    sa.Column('konsultation_id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['konsultation_id'], ['vorherige_konsultation.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('konsultation_id', 'verarbeitung_id')
    )
    op.create_table('dsgvo_strafen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strafe', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pflicht_grundprinzip',
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.Column('grundprinzip_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['grundprinzip_id'], ['grund_prinzipien_dsgvo.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('pflicht_id', 'grundprinzip_id')
    )
    op.create_table('definition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('verstoss_strafe',
    sa.Column('verstoss_id', sa.INTEGER(), nullable=False),
    sa.Column('strafe_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['strafe_id'], ['dsgvo_strafen.id'], ),
    sa.ForeignKeyConstraint(['verstoss_id'], ['verstoss.id'], ),
    sa.PrimaryKeyConstraint('verstoss_id', 'strafe_id')
    )
    op.create_table('recht_akteur',
    sa.Column('recht_id', sa.INTEGER(), nullable=False),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['recht_id'], ['recht.id'], ),
    sa.PrimaryKeyConstraint('recht_id', 'akteur_id')
    )
    op.create_table('drittland',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('angemessenheit', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tom_zu_schutz_ziel',
    sa.Column('fk_tom_id', sa.INTEGER(), nullable=False),
    sa.Column('fk_schutz_ziel_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fk_schutz_ziel_id'], ['schutzziel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_tom_id'], ['technische_organisatorisch_masnahmen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fk_tom_id', 'fk_schutz_ziel_id')
    )
    op.create_table('uebermittlungs_regelung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=False),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datenpanne_pflichten',
    sa.Column('datenpanne_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['datenpanne_id'], ['datenpanne.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('datenpanne_id', 'pflicht_id')
    )
    op.create_table('recht',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recht', sa.VARCHAR(length=255), nullable=False),
    sa.Column('erklaerung', sa.TEXT(), nullable=True),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verhaltenskodex_akteur',
    sa.Column('verhaltenskodex_id', sa.INTEGER(), nullable=False),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verhaltenskodex_id'], ['verhaltenskodex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verhaltenskodex_id', 'akteur_id')
    )
    op.create_table('dsfas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('datum_erstellung', sa.DATE(), nullable=True),
    sa.Column('datum_letzte_pruefung', sa.DATE(), nullable=True),
    sa.Column('rest_risiko_stufe', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verarbeitung_id')
    )
    op.create_index(op.f('ix_dsfas_id'), 'dsfas', ['id'], unique=False)
    op.create_table('sanktion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('typ', sa.VARCHAR(length=50), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=False),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sicherheitsmasnahme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('masnahme', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), nullable=False),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verarbeitung_empfaengerkategorie',
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.Column('empfaengerkategorie_id', sa.INTEGER(), nullable=False),
    sa.Column('kommentar', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['empfaengerkategorie_id'], ['empfaenger_kategorie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verarbeitung_id', 'empfaengerkategorie_id')
    )
    op.create_table('aufgaben',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(length=255), nullable=True),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aufgaben_id'), 'aufgaben', ['id'], unique=False)
    op.create_table('verhaltenskodex',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=False),
    sa.Column('herausgeber_verband', sa.VARCHAR(length=255), nullable=True),
    sa.Column('genehmigungsbehoerde', sa.VARCHAR(length=255), nullable=True),
    sa.Column('article_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('absatz_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.Column('drittland_geeignet', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_verhaltenskodex_id'), 'verhaltenskodex', ['id'], unique=False)
    op.create_table('sanktion_verstoss',
    sa.Column('sanktion_id', sa.INTEGER(), nullable=False),
    sa.Column('verstoss_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sanktion_id'], ['sanktion.id'], ),
    sa.ForeignKeyConstraint(['verstoss_id'], ['verstoss.id'], ),
    sa.PrimaryKeyConstraint('sanktion_id', 'verstoss_id')
    )
    op.create_table('pflicht_verstoss',
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.Column('verstoss_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.ForeignKeyConstraint(['verstoss_id'], ['verstoss.id'], ),
    sa.PrimaryKeyConstraint('pflicht_id', 'verstoss_id')
    )
    op.create_table('gemeinsame_verantwortlichkeit_verarbeitung',
    sa.Column('gemeinsame_verantwortlichkeit_id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gemeinsame_verantwortlichkeit_id'], ['gemeinsame_verantwortlichkeit.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('gemeinsame_verantwortlichkeit_id', 'verarbeitung_id')
    )
    op.create_table('verarbeitung_zu_tom',
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.Column('tom_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tom_id'], ['technische_organisatorisch_masnahmen.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('verarbeitung_id', 'tom_id')
    )
    op.create_table('rechtsgrundlage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rechts_grundlage', sa.VARCHAR(length=255), nullable=False),
    sa.Column('artikel_number', sa.INTEGER(), nullable=False),
    sa.Column('absatz_number', sa.INTEGER(), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rechtsgrundlage_id'), 'rechtsgrundlage', ['id'], unique=False)
    op.create_table('aufbewahrungsfrist_datenkategorie',
    sa.Column('aufbewahrungsfrist_id', sa.INTEGER(), nullable=False),
    sa.Column('datenkategorie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['aufbewahrungsfrist_id'], ['aufbewahrungsfrist.id'], ),
    sa.ForeignKeyConstraint(['datenkategorie_id'], ['dsgvo_datenkategorie.id'], ),
    sa.PrimaryKeyConstraint('aufbewahrungsfrist_id', 'datenkategorie_id')
    )
    op.create_table('rechtlicher_ausloeser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ausloeser', sa.VARCHAR(length=255), nullable=False),
    sa.Column('article_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('absatz_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_empfehlung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('typ', sa.VARCHAR(length=50), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=False),
    sa.Column('verbindlichkeit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('artikle_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datenpanne_akteur',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datenpanne_id', sa.INTEGER(), nullable=False),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.Column('rolle', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['datenpanne_id'], ['datenpanne.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datenpanne_akteur_id'), 'datenpanne_akteur', ['id'], unique=False)
    op.create_table('gruppe_verarbeitungstaetigkeit',
    sa.Column('gruppe_id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitungstaetigkeit_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gruppe_id'], ['gruppe.id'], ),
    sa.ForeignKeyConstraint(['verarbeitungstaetigkeit_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('gruppe_id', 'verarbeitungstaetigkeit_id')
    )
    op.create_table('uebermittlung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fk_verarbeitungstaetigkeit_id', sa.INTEGER(), nullable=False),
    sa.Column('fk_drittland_id', sa.INTEGER(), nullable=False),
    sa.Column('fk_uebertragungsgarantie_id', sa.INTEGER(), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('gueltig_ab', sa.DATE(), nullable=True),
    sa.Column('fk_ausnahme_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fk_ausnahme_id'], ['uebermittlungsausnahme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_drittland_id'], ['drittland.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_uebertragungsgarantie_id'], ['uebertragungsgarantie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_verarbeitungstaetigkeit_id'], ['verarbeitungstaetigkeiten.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ausnahme_pflicht',
    sa.Column('ausnahme_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ausnahme_id'], ['ausnahme.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('ausnahme_id', 'pflicht_id')
    )
    op.create_table('datenpanne',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('gesetzliche_grundlage', sa.VARCHAR(length=255), nullable=True),
    sa.Column('meldefrist_stunden', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_datenpanne_id'), 'datenpanne', ['id'], unique=False)
    op.create_table('aufbewahrungsfrist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dauer_in_tagen', sa.INTEGER(), nullable=True),
    sa.Column('article_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('absatz_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avv_verarbeitungstaetigkeit',
    sa.Column('avv_id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['avv_id'], ['auftragsverarbeitungs_vertrag.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('avv_id', 'verarbeitung_id')
    )
    op.create_table('verarbeitungstaetigkeiten',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('verarbeitungsform_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['verarbeitungsform_id'], ['verarbeitungsform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verarbeitungstaetigkeiten_id'), 'verarbeitungstaetigkeiten', ['id'], unique=False)
    op.create_table('rechtsgrundlage_pflicht',
    sa.Column('rechtsgrundlage_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.ForeignKeyConstraint(['rechtsgrundlage_id'], ['rechtsgrundlage.id'], ),
    sa.PrimaryKeyConstraint('rechtsgrundlage_id', 'pflicht_id')
    )
    op.create_table('verarbeitung_frist',
    sa.Column('verarbeitungstaetigkeit_id', sa.INTEGER(), nullable=False),
    sa.Column('frist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['frist_id'], ['aufbewahrungsfrist.id'], ),
    sa.ForeignKeyConstraint(['verarbeitungstaetigkeit_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('verarbeitungstaetigkeit_id', 'frist_id')
    )
    op.create_table('verarbeitungsform',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('artikel_relevant', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bedingung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ausnahme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ausnahme_id'], ['ausnahme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interne_personen_gruppen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pflicht',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('artikel_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=50), nullable=True),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.Column('kategorie_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['kategorie_id'], ['pflichtenkategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gemeinsame_verantwortlichkeit_pflichten',
    sa.Column('gemeinsame_verantwortlichkeit_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gemeinsame_verantwortlichkeit_id'], ['gemeinsame_verantwortlichkeit.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('gemeinsame_verantwortlichkeit_id', 'pflicht_id')
    )
    op.create_table('vorherige_konsultation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('gesetzliche_grundlage', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dsfa_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dsfa_id'], ['dsfas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dsfa_id')
    )
    op.create_index(op.f('ix_vorherige_konsultation_id'), 'vorherige_konsultation', ['id'], unique=False)
    op.create_table('auftragsverarbeitungs_vertrag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(length=255), nullable=False),
    sa.Column('gesetzliche_grundlage', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avv_pflichten',
    sa.Column('avv_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['avv_id'], ['auftragsverarbeitungs_vertrag.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('avv_id', 'pflicht_id')
    )
    op.create_table('recht_bedingung',
    sa.Column('recht_id', sa.INTEGER(), nullable=False),
    sa.Column('bedingung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bedingung_id'], ['bedingung.id'], ),
    sa.ForeignKeyConstraint(['recht_id'], ['recht.id'], ),
    sa.PrimaryKeyConstraint('recht_id', 'bedingung_id')
    )
    op.create_table('sicherheitsniveau',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('niveau', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avv_tomassnahmen',
    sa.Column('avv_id', sa.INTEGER(), nullable=False),
    sa.Column('tom_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['avv_id'], ['auftragsverarbeitungs_vertrag.id'], ),
    sa.ForeignKeyConstraint(['tom_id'], ['technische_organisatorisch_masnahmen.id'], ),
    sa.PrimaryKeyConstraint('avv_id', 'tom_id')
    )
    op.create_table('verhaltenskodex_prinzip',
    sa.Column('verhaltenskodex_id', sa.INTEGER(), nullable=False),
    sa.Column('prinzip_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['prinzip_id'], ['grund_prinzipien_dsgvo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verhaltenskodex_id'], ['verhaltenskodex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verhaltenskodex_id', 'prinzip_id')
    )
    op.create_table('risikofaktoren',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(), nullable=True),
    sa.Column('gewichtung', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risikofaktoren_id'), 'risikofaktoren', ['id'], unique=False)
    op.create_table('dsgvo_ziel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ziel', sa.VARCHAR(length=255), nullable=False),
    sa.Column('article_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('absatz_number', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datenpanne_verarbeitung',
    sa.Column('datenpanne_id', sa.INTEGER(), nullable=False),
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['datenpanne_id'], ['datenpanne.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('datenpanne_id', 'verarbeitung_id')
    )
    op.create_table('schutzziel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('schutz_ziel', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schutzziel_id'), 'schutzziel', ['id'], unique=False)
    op.create_table('konsultation_pflichten',
    sa.Column('konsultation_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['konsultation_id'], ['vorherige_konsultation.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('konsultation_id', 'pflicht_id')
    )
    op.create_table('zweck',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zweck_id'), 'zweck', ['id'], unique=False)
    op.create_table('uebermittlungs_regelung_garantie',
    sa.Column('regelung_id', sa.INTEGER(), nullable=False),
    sa.Column('garantie_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['garantie_id'], ['uebertragungsgarantie.id'], ),
    sa.ForeignKeyConstraint(['regelung_id'], ['uebermittlungs_regelung.id'], ),
    sa.PrimaryKeyConstraint('regelung_id', 'garantie_id')
    )
    op.create_table('gruppe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dsgvo_akteur',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('akteur', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsgvo_akteur_id'), 'dsgvo_akteur', ['id'], unique=False)
    op.create_table('verarbeitung_risikofaktoren',
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.Column('risikofaktor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['risikofaktor_id'], ['risikofaktoren.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('verarbeitung_id', 'risikofaktor_id')
    )
    op.create_table('aufbewahrungsfrist_zweck',
    sa.Column('aufbewahrungsfrist_id', sa.INTEGER(), nullable=False),
    sa.Column('zweck_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['aufbewahrungsfrist_id'], ['aufbewahrungsfrist.id'], ),
    sa.ForeignKeyConstraint(['zweck_id'], ['zweck.id'], ),
    sa.PrimaryKeyConstraint('aufbewahrungsfrist_id', 'zweck_id')
    )
    op.create_table('uebermittlungs_regelung_ausnahme',
    sa.Column('regelung_id', sa.INTEGER(), nullable=False),
    sa.Column('ausnahme_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ausnahme_id'], ['uebermittlungsausnahme.id'], ),
    sa.ForeignKeyConstraint(['regelung_id'], ['uebermittlungs_regelung.id'], ),
    sa.PrimaryKeyConstraint('regelung_id', 'ausnahme_id')
    )
    op.create_table('verarbeitung_rechtsgrundlage',
    sa.Column('verarbeitung_id', sa.INTEGER(), nullable=False),
    sa.Column('rechtsgrundlage_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rechtsgrundlage_id'], ['rechtsgrundlage.id'], ),
    sa.ForeignKeyConstraint(['verarbeitung_id'], ['verarbeitungstaetigkeiten.id'], ),
    sa.PrimaryKeyConstraint('verarbeitung_id', 'rechtsgrundlage_id')
    )
    op.create_table('gemeinsame_verantwortlichkeit_dsfa',
    sa.Column('gemeinsame_verantwortlichkeit_id', sa.INTEGER(), nullable=False),
    sa.Column('dsfa_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dsfa_id'], ['dsfas.id'], ),
    sa.ForeignKeyConstraint(['gemeinsame_verantwortlichkeit_id'], ['gemeinsame_verantwortlichkeit.id'], ),
    sa.PrimaryKeyConstraint('gemeinsame_verantwortlichkeit_id', 'dsfa_id')
    )
    op.create_table('grund_prinzipien_dsgvo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prinzip', sa.VARCHAR(length=255), nullable=False),
    sa.Column('article_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('absatz_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('literature', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grund_prinzipien_dsgvo_id'), 'grund_prinzipien_dsgvo', ['id'], unique=False)
    op.create_table('voraussetzung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(length=500), nullable=False),
    sa.Column('typ', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rechtsgrundlage_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['rechtsgrundlage_id'], ['rechtsgrundlage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voraussetzung_id'), 'voraussetzung', ['id'], unique=False)
    op.create_table('gemeinsame_verantwortlichkeit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('gesetzliche_grundlage', sa.VARCHAR(length=255), nullable=True),
    sa.Column('transparenzvereinbarung', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemeinsame_verantwortlichkeit_id'), 'gemeinsame_verantwortlichkeit', ['id'], unique=False)
    op.create_table('technische_organisatorisch_masnahmen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('masnahme', sa.VARCHAR(length=255), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(), nullable=True),
    sa.Column('is_technical', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technische_organisatorisch_masnahmen_id'), 'technische_organisatorisch_masnahmen', ['id'], unique=False)
    op.create_table('verstoss',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('beschreibung', sa.TEXT(), nullable=True),
    sa.Column('schweregrad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vorsatz', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datenpanne_risikofaktor',
    sa.Column('datenpanne_id', sa.INTEGER(), nullable=False),
    sa.Column('risikofaktor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['datenpanne_id'], ['datenpanne.id'], ),
    sa.ForeignKeyConstraint(['risikofaktor_id'], ['risikofaktoren.id'], ),
    sa.PrimaryKeyConstraint('datenpanne_id', 'risikofaktor_id')
    )
    op.create_table('pflicht_bedingung',
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.Column('bedingung_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['bedingung_id'], ['bedingung.id'], ),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.PrimaryKeyConstraint('pflicht_id', 'bedingung_id')
    )
    op.create_table('sicherheitsmassnahmen_schutzziel',
    sa.Column('fk_sicherheitsmassnahmen_id', sa.INTEGER(), nullable=False),
    sa.Column('fk_schutzziel_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fk_schutzziel_id'], ['schutzziel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_sicherheitsmassnahmen_id'], ['sicherheitsmasnahme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fk_sicherheitsmassnahmen_id', 'fk_schutzziel_id')
    )
    op.create_table('dsgvo_datenkategorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_sensible', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechtlicher_ausloeser_pflicht',
    sa.Column('rechtlicher_ausloeser_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.ForeignKeyConstraint(['rechtlicher_ausloeser_id'], ['rechtlicher_ausloeser.id'], ),
    sa.PrimaryKeyConstraint('rechtlicher_ausloeser_id', 'pflicht_id')
    )
    op.create_table('pflicht_tom',
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.Column('tom_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.ForeignKeyConstraint(['tom_id'], ['technische_organisatorisch_masnahmen.id'], ),
    sa.PrimaryKeyConstraint('pflicht_id', 'tom_id')
    )
    op.create_table('recht_pflicht',
    sa.Column('recht_id', sa.INTEGER(), nullable=False),
    sa.Column('pflicht_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pflicht_id'], ['pflicht.id'], ),
    sa.ForeignKeyConstraint(['recht_id'], ['recht.id'], ),
    sa.PrimaryKeyConstraint('recht_id', 'pflicht_id')
    )
    op.create_table('avv_akteure',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('avv_id', sa.INTEGER(), nullable=False),
    sa.Column('akteur_id', sa.INTEGER(), nullable=False),
    sa.Column('rolle', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['akteur_id'], ['dsgvo_akteur.id'], ),
    sa.ForeignKeyConstraint(['avv_id'], ['auftragsverarbeitungs_vertrag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avv_akteure_id'), 'avv_akteure', ['id'], unique=False)
    # ### end Alembic commands ###
