"""add resons table with rel

Revision ID: e89aed87a79a
Revises: f5a7264dfbdf
Create Date: 2026-08-13 11:04:19.951912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89aed87a79a'
down_revision: Union[str, Sequence[str], None] = 'f5a7264dfbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gdpr_articles')
    op.drop_table('criterion_article_association')
    op.drop_table('gdpr_criteria')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gdpr_criteria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterion_article_association',
    sa.Column('criterion_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['gdpr_articles.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['gdpr_criteria.id'], ),
    sa.PrimaryKeyConstraint('criterion_id', 'article_id')
    )
    op.create_table('gdpr_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_number', sa.VARCHAR(length=2), nullable=False),
    sa.Column('paragraph', sa.VARCHAR(length=2), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=2), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
