"""add component name table in fallback table

Revision ID: ef0b242cd6d7
Revises: 78de75c34a5b
Create Date: 2026-09-06 17:24:09.224278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0b242cd6d7'
down_revision: Union[str, Sequence[str], None] = '78de75c34a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fallback_llm')
    op.drop_table('reason')
    op.drop_table('gdpr_criteria')
    op.drop_table('criterion_article_association')
    op.drop_table('gdpr_articles')
    op.drop_table('category_reason_association')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_reason_association',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('reason_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['reason_id'], ['reason.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'reason_id')
    )
    op.create_table('gdpr_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_number', sa.VARCHAR(length=2), nullable=False),
    sa.Column('paragraph', sa.VARCHAR(length=2), nullable=True),
    sa.Column('literature', sa.VARCHAR(length=2), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterion_article_association',
    sa.Column('criterion_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['gdpr_articles.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['gdpr_criteria.id'], ),
    sa.PrimaryKeyConstraint('criterion_id', 'article_id')
    )
    op.create_table('gdpr_criteria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reason',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reason')
    )
    op.create_table('fallback_llm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('model_url', sa.TEXT(), nullable=False),
    sa.Column('env_api_key_name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
